version: 2
builds:
- id: skip-binaries
  skip: true

release:
  github:
    owner: charmingruby
    name: fgp
  prerelease: auto

archives:
- id: source
  meta: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"
  formats:
  - tar.gz
  files:
  - go.mod
  - Makefile
  - fp/**
  - option/**
  - result/**
  - seq/**
  - task/**
  - internal/**

source:
  enabled: true

checksum:
  name_template: "checksums.txt"

sboms:
- artifacts: source
  cmd: builtin:syft

changelog:
  use: github
