version: 2
builds: []

release:
  github:
    owner: charmingruby
    name: fgp
  prerelease: auto

archives:
- id: source
  format: tar.gz
  files:
  - go.mod
  - go.sum
  - Makefile
  - fp/**
  - option/**
  - result/**
  - seq/**
  - task/**
  - internal/**

source:
  enabled: true

checksum:
  name_template: "checksums.txt"

sboms:
- artifacts:
  - source

changelog:
  use: github
